MODEL:
  TYPE: polyvit
  NAME: pvit_b_1kscratch
  PRETRAINED: False
  CARD: "vit_base_patch16_224"
  # DROP_RATE: 0.1
  # CARD: "timm/vit_base_patch16_224.augreg_in1k"

DATA:
  # BATCH_SIZE: 512
  BATCH_SIZE: 256
  NUM_WORKERS: 16
  MEAN: [0.5, 0.5, 0.5]
  STD: [0.5, 0.5, 0.5]

TRAIN: 
  # WARMUP_EPOCHS: 0
  # WARMUP_LR: 1e-3
  # BASE_LR: 1e-3
  # MIN_LR: 1e-3
  # WEIGHT_DECAY: 0.01
  EPOCHS: 200

# AUG:
#   AUTO_AUGMENT: '3a'



# TRAIN: 
#   WARMUP_EPOCHS: 0
#   WARMUP_LR: 1e-4
#   BASE_LR: 1e-4
#   MIN_LR: 1e-4
#   WEIGHT_DECAY: 0.001
#   EPOCHS: 100

# TRAIN: 
#   WARMUP_EPOCHS: 0
#   WARMUP_LR: 3e-4
#   BASE_LR: 3e-4
#   MIN_LR: 3e-4
#   WEIGHT_DECAY: 0.001
#   EPOCHS: 100

# TRAIN: 
#   WARMUP_EPOCHS: 0
#   WARMUP_LR: 1e-4
#   BASE_LR: 1e-4
#   MIN_LR: 1e-4
#   WEIGHT_DECAY: 0.01
#   EPOCHS: 100

# TRAIN: 
#   WARMUP_EPOCHS: 0
#   WARMUP_LR: 1e-4
#   BASE_LR: 1e-4
#   MIN_LR: 1e-4
#   WEIGHT_DECAY: 0.1
#   EPOCHS: 100

# TRAIN:
#   WARMUP_EPOCHS: 0
#   WARMUP_LR: 1e-5
#   BASE_LR: 1e-5
#   MIN_LR: 1e-5
#   WEIGHT_DECAY: 0.01
#   EPOCHS: 30

# TRAIN: 
#   WARMUP_EPOCHS: 0
#   WARMUP_LR: 1e-3
#   BASE_LR: 1e-3
#   MIN_LR: 1e-3
#   WEIGHT_DECAY: 0.1
#   EPOCHS: 30

# TRAIN: 
#   WARMUP_EPOCHS: 0
#   WARMUP_LR: 1e-4
#   BASE_LR: 1e-4
#   MIN_LR: 1e-4
#   WEIGHT_DECAY: 0.1
#   EPOCHS: 30

# TRAIN:
#   WARMUP_EPOCHS: 20
#   WARMUP_LR: 1e-6
#   BASE_LR: 1e-5
#   MIN_LR: 1e-5
#   WEIGHT_DECAY: 0.1
# TRAIN:
#   WARMUP_EPOCHS: 20
#   WARMUP_LR: 1e-6
#   BASE_LR: 1e-4
#   MIN_LR: 1e-5
#   WEIGHT_DECAY: 0.1

# TRAIN:
#   WARMUP_EPOCHS: 20
#   WARMUP_LR: 1e-5
#   BASE_LR: 1e-3
#   MIN_LR: 1e-5
#   WEIGHT_DECAY: 0.1
