MODEL:
  TYPE: twins
  NAME: twins_svts_b_scratch
  PRETRAINED: False
  CARD: "twins_svt_base"
  DROP_PATH_RATE: 0.3
DATA:
  BATCH_SIZE: 128
  NUM_WORKERS: 16

TRAIN:
  WARMUP_EPOCHS: 5
  WARMUP_LR: 1e-6
  BASE_LR: 5e-4
  MIN_LR: 1e-5
  WEIGHT_DECAY: 0.1
