MODEL:
  TYPE: twins
  NAME: twins_svts_w
  PRETRAINED: False
  CARD: "twins_svt_small"

DATA:
  BATCH_SIZE: 256
  NUM_WORKERS: 8

TRAIN:
  WARMUP_EPOCHS: 10
  WARMUP_LR: 1e-6
  BASE_LR: 1e-3
  MIN_LR: 1e-5
  WEIGHT_DECAY: 0.1
