<<<<<<< HEAD
MODEL:
  TYPE: vit_poly
  NAME: poly_vit_tiny_0221
  PRETRAINED: "model"
DATA:
  BATCH_SIZE: 128
  NUM_WORKERS: 24
=======
# patch size 4 and window size 7
MODEL:
  TYPE: vit_poly
  NAME: poly_vit_tiny_0221
  START_EVAL: True
DATA:
  BATCH_SIZE: 128
  NUM_WORKERS: 1
TRAIN:
  WARMUP_EPOCHS: 5
  WARMUP_LR: 1e-8
>>>>>>> 7cddd7a2be99043f438e7c947c35b2cb1f181164
