# patch size 4 and window size 7
MODEL:
  TYPE: swin_poly
  NAME: poly_swin_tiny_0215
  DROP_PATH_RATE: 0.2
  SWIN:
    EMBED_DIM: 96
    DEPTHS: [ 2, 2, 6, 2 ]
    NUM_HEADS: [ 3, 6, 12, 24 ]
    WINDOW_SIZE: 7
DATA:
  BATCH_SIZE: 128
  NUM_WORKERS: 8