MODEL:
  TYPE: polyvit
  NAME: pvit_407
  PRETRAINED: "model"

DATA:
  BATCH_SIZE: 256
  NUM_WORKERS: 8
  # BATCH_SIZE: 128 # eval params 
  # NUM_WORKERS: 8 
TRAIN:
  WARMUP_EPOCHS: 20
  WARMUP_LR: 1e-6
  BASE_LR: 1e-4
  MIN_LR: 1e-5
  WEIGHT_DECAY: 0.01

# TRAIN:
#   WARMUP_EPOCHS: 20
#   WARMUP_LR: 1e-9
#   BASE_LR: 1e-7
#   MIN_LR: 1e-8
#   WEIGHT_DECAY: 0.03

